### ISSUE TITLE
Github Contribution not showing

### ISSUE THREAD

**Issue by priyansh18** [jugshaurya/PortfolioProject#11]
@jugshaurya Plz help..
![Screenshot from 2020-12-28 20-14-14](https://user-images.githubusercontent.com/48357563/103221731-51474e80-4949-11eb-97ff-eaa630779943.png)

**Comment by jugshaurya** [comment]
@priyansh18 Thanks for reporting this.

Github actually added dark mode recently, that's why they added CSS variable names to colors so they could easily toggle between colors. so need to change this code.
 
![Screenshot from 2020-12-28 20-17-49](https://user-images.githubusercontent.com/39825643/103222098-ef3b1900-4949-11eb-86d5-edffe913f3d8.png)

**Comment by jugshaurya** [comment]
@priyansh18, wait let me change and make a commit

**Comment by jugshaurya** [comment]
@priyansh18 have a look now

**Comment by priyansh18** [comment]
Thanks, @jugshaurya  for the help

![Screenshot from 2020-12-28 21-01-37](https://user-images.githubusercontent.com/48357563/103225453-f06f4480-494f-11eb-919d-c35b76216757.png)
